package com.amz.statusly;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.cardview.widget.CardView;import androidx.recyclerview.widget.GridLayoutManager;import androidx.recyclerview.widget.RecyclerView;import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;import java.util.*;

public class MainActivity extends AppCompatActivity {
 RecyclerView rvVideo,rvPhoto; SwipeRefreshLayout videoRefresh,photoRefresh; TextView videoBtn,photoBtn; CardView photoConfirm; ArrayList<String> videos=new ArrayList<>(),photos=new ArrayList<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(com.amz.statusly.R.layout.activity_main);rvVideo=findViewById(R.id.rvVideo);rvPhoto=findViewById(R.id.rvPhoto);videoRefresh=findViewById(R.id.swipeRefreshLayout);photoRefresh=findViewById(R.id.swipeRefreshLayoutPhoto);videoBtn=findViewById(R.id.videoBtn);photoBtn=findViewById(R.id.photoBtn);photoConfirm=findViewById(R.id.photoConfirm);videoBtn.setText("Videos");photoBtn.setText("Photos");videoRefresh.setOnRefreshListener(()->{loadVideos();videoRefresh.setRefreshing(false);});photoRefresh.setOnRefreshListener(()->{loadPhotos();photoRefresh.setRefreshing(false);});videoBtn.setOnClickListener(v->showVideos());photoBtn.setOnClickListener(v->showPhotos());requestPermission();}
 void requestPermission(){if(Build.VERSION.SDK_INT>=33){requestPermissions(new String[]{Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_IMAGES},9);}else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},9);else loadVideos();}
 @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==9)loadVideos();}
 void showVideos(){videoRefresh.setVisibility(View.VISIBLE);photoRefresh.setVisibility(View.GONE);photoConfirm.setVisibility(View.GONE);loadVideos();}
 void showPhotos(){videoRefresh.setVisibility(View.GONE);photoRefresh.setVisibility(View.VISIBLE);loadPhotos();}
 void loadVideos(){videos.clear();Cursor c=getContentResolver().query(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,new String[]{MediaStore.Video.Media.DATA},null,null,MediaStore.Video.Media.DATE_MODIFIED+" DESC");if(c!=null){while(c.moveToNext())videos.add(c.getString(0));c.close();}rvVideo.setLayoutManager(new GridLayoutManager(this,3));rvVideo.setAdapter(new MediaAdapter(videos,true));}
 void loadPhotos(){photos.clear();Cursor c=getContentResolver().query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,new String[]{MediaStore.Images.Media.DATA},null,null,MediaStore.Images.Media.DATE_MODIFIED+" DESC");if(c!=null){while(c.moveToNext())photos.add(c.getString(0));c.close();}rvPhoto.setLayoutManager(new GridLayoutManager(this,3));rvPhoto.setAdapter(new MediaAdapter(photos,false));}
 class MediaAdapter extends RecyclerView.Adapter<VH>{ArrayList<String> a;boolean video;MediaAdapter(ArrayList<String>x,boolean v){a=x;video=v;}public VH onCreateViewHolder(android.view.ViewGroup p,int v){ImageView i=new ImageView(MainActivity.this);i.setLayoutParams(new ViewGroup.LayoutParams(-1,320));i.setScaleType(ImageView.ScaleType.CENTER_CROP);return new VH(i);}public void onBindViewHolder(VH h,int pos){String path=a.get(pos);android.graphics.Bitmap bm=video?android.media.ThumbnailUtils.createVideoThumbnail(path,android.provider.MediaStore.Video.Thumbnails.MINI_KIND):android.graphics.BitmapFactory.decodeFile(path);h.i.setImageBitmap(bm);h.i.setOnClickListener(v->{if(video){Intent in=new Intent(MainActivity.this,VideoCompressActivity.class);ArrayList<String>x=new ArrayList<>();x.add(path);in.putStringArrayListExtra("urls",x);startActivity(in);}else{Intent in=new Intent(MainActivity.this,PhotoCompressActivity.class);in.putExtra("path",path);startActivity(in);}});}public int getItemCount(){return a.size();}}
 static class VH extends RecyclerView.ViewHolder{ImageView i;VH(ImageView v){super(v);i=v;}}
}
