package com.amz.statusly;

import android.content.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.cardview.widget.CardView;import com.arthenica.mobileffmpeg.Config;import com.google.android.material.progressindicator.LinearProgressIndicator;import java.io.*;import java.util.*;

public class VideoCompressActivity extends AppCompatActivity{
 LinearLayout clipBox;ImageView background,compress,withoutWater,closeBtn;CardView stop,shareBtn;LinearLayout shareBar;LinearProgressIndicator progress;String input;String output;long duration;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_video_compress);clipBox=findViewById(R.id.clipBox);background=findViewById(R.id.background);compress=findViewById(R.id.compress);withoutWater=findViewById(R.id.withoutWater);closeBtn=findViewById(R.id.closeBtn);stop=findViewById(R.id.stop);shareBtn=findViewById(R.id.shareBtn);shareBar=findViewById(R.id.shareBar);shareBar.setVisibility(View.GONE);stop.setVisibility(View.GONE);input=getIntent().getStringArrayListExtra("urls").get(0);duration=0;try{android.media.MediaMetadataRetriever r=new android.media.MediaMetadataRetriever();r.setDataSource(input);String d=r.extractMetadata(android.media.MediaMetadataRetriever.METADATA_KEY_DURATION);duration=Long.parseLong(d==null?"0":d);try{r.release();}catch(IOException ignored){}}catch(Exception e){};compress.setOnClickListener(v->encode(false));withoutWater.setOnClickListener(v->encode(false));closeBtn.setOnClickListener(v->finish());stop.setOnClickListener(v->{try{Config.cancel();}catch(Throwable ignored){}finish();});shareBtn.setOnClickListener(v->share());}
 void encode(boolean watermark){compress.setVisibility(View.GONE);withoutWater.setVisibility(View.GONE);stop.setVisibility(View.VISIBLE);output=new File(getCacheDir(),"Output/"+UUID.randomUUID()+".mp4").getAbsolutePath();new File(getCacheDir(),"Output").mkdirs();long j=duration;double buf=j<6000?1900:j<11000?3800:j<16000?5700:7600;String vf="scale=1280:trunc(ow/a/2)*2";String cmd="-i \""+input+"\" -filter:v \""+vf+"\" -c:v libx264 -crf 22 -maxrate 3800k -bufsize "+(int)buf+"k -r 29.97 -ar 44.1k -b:a 128k \""+output+"\"";new Thread(()->{int rc;try{rc=Config.execute(cmd);}catch(Throwable t){runOnUiThread(()->fail(t.toString()));return;}int code=rc;runOnUiThread(()->{stop.setVisibility(View.GONE);if(code==0){shareBar.setVisibility(View.VISIBLE);Toast.makeText(this,"Compressed successfully",Toast.LENGTH_SHORT).show();}else fail("FFmpeg return code: "+code+"\n"+Config.getLastCommandOutput());});}).start();}
 void fail(String s){stop.setVisibility(View.GONE);compress.setVisibility(View.VISIBLE);withoutWater.setVisibility(View.VISIBLE);new AlertDialog.Builder(this).setTitle("Compression failed").setMessage(s).setPositiveButton("OK",null).show();}
 void share(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("video/mp4");i.putExtra(Intent.EXTRA_STREAM,Uri.parse("file://"+output));startActivity(Intent.createChooser(i,"Share Video"));}
}
